# The name of the application (no spaces)
app_name: VTdeepdive

# A brief description of the app.
description : 

# Your first and last name
user: Sean Malloy

# Your email
email: malloyse@vt.edu

# The primary language the application is written in - will be used for installing dependencies
# Current options are Python, R, and Go
language: Python

# You can choose to specify a list of dictionaries, a list of terms, or both.
# If both dictionaries and terms are provided, all terms in the dictionary PLUS
# all listed terms will be used
dictionaries: [instruments]

terms: [theremin]
